package sk.martinvanco.monad.facts.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * `monad-facts.json` — the Foundation-track reading matter bundled with the app (IP-146).
 *
 * Generated by `monad-knowledge edu deck facts` from the `core` deck notes and committed under
 * `composeResources/files/`. **Bundled rather than served, and that is a measurement decision.**
 * The fleet has no access point, a probe dwell is thirty seconds long, and a participant standing
 * still in a library basement may have no route to anything. A fact that arrives after the
 * countdown has finished is worse than no fact at all, so nothing here touches the network.
 *
 * Refreshing the content is therefore an app build. That is the price, it is paid once per release,
 * and `tests/test_edu_deck_facts.py` fails when the committed file drifts from the deck notes.
 */
@Serializable
data class FactDeckDto(
    @SerialName("schema_version") val schemaVersion: Int = 0,
    @SerialName("facts_version") val factsVersion: String = "",
    val facts: List<FactDto> = emptyList(),
)

/**
 * One panel of reading matter.
 *
 * Since IP-151 every body is a curator-approved `dwell:` text of a deck card — written to the 11 s
 * panel budget, swiped right in the Defense app before it ships — plus that card's own heading. The
 * exporter selects; it never rewrites. So a fact shown here says exactly what the card says, which
 * is what makes it safe to put in front of a participant with no reviewer in the loop.
 */
@Serializable
data class FactDto(
    val id: String,
    @SerialName("card_id") val cardId: String,
    val deck: String,
    val title: String,
    /** `foundation` — the definition. `wild` — the card's own worked instance. */
    val flavour: String = "foundation",
    val body: String,
    /**
     * A curator marked this instance as an easter egg. Shown more often and dressed differently,
     * because the absurd ones are what make somebody take the quest again.
     */
    val surprise: Boolean = false,
    /** One dry line after a `wild` fact (IP-151, schema 2). Human-approved like the body. */
    val quip: String? = null,
)
